version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
    username: x-access-token
    password: no-secret-required
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Oslo"
    registries:
      - "maven-github"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
