apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-emailer
  namespace: teampam
  labels:
    team: teampam
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: 3000ms
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  webproxy: false
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  envFrom:
    - secret: pam-emailer
  accessPolicy:
    inbound:
      rules:
        - application: pam-samtykke-api
        - application: pam-moteplass-api
        - application: pam-interesse-api
        - application: pam-survey-api
    outbound:
      external:
        - host: login.microsoftonline.com
          ports:
            - port: 443
              name: https
              protocol: HTTPS
        - host: graph.microsoft.com
          ports:
            - port: 443
              name: https
              protocol: HTTPS
