apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-emailer
  namespace: teampam
  labels:
    team: teampam
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: 3500ms
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  webproxy: false
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
  {{#each ingress as |url|}}
      - {{url}}
  {{/each}}
  env:
    - name: DB_CONNECTION_POOL_SIZE
      value: {{database_connection_pool_size}}
  envFrom:
    - secret: pam-emailer
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: {{database_tier}}
        highAvailability: {{database_high_availability}}
        databases:
          - name: pam-emailer-db
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: pam-samtykke-api
        - application: pam-interesse-api
        - application: pam-survey-api
        - application: pam-aduser
    outbound:
      external:
        - host: login.microsoftonline.com
          ports:
            - port: 443
        - host: graph.microsoft.com
          ports:
            - port: 443
