spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:35432}/${DB_DATABASE:pam-emailer}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

logging:
  config: