micronaut:
  application:
    name: pam-emailer
  http:
    client:
      read-timeout: 30s
  metrics:
    enabled: true
    sensitive: false
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: false
  env:
    deduction: false
endpoints:
  metrics:
    enabled: true
  prometheus:
    sensitive: false

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

