spring:
  application:
    name: pam-emailer

  datasource:
    url: jdbc:postgresql://${DB_HOST:}:${DB_PORT:}/${DB_DATABASE:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5

management:
  endpoints.web.exposure.include: prometheus
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  prometheus.metrics.export.enabled: true