spring:
  application:
    name: pam-emailer

management:
  endpoints.web.exposure.include: prometheus
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  prometheus.metrics.export.enabled: true