spring:
  application:
    name: pam-emailer

  datasource:
    url: ${db.jdbc.url}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5

management:
  endpoints.web.exposure.include: prometheus
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  prometheus.metrics.export.enabled: true