spring:
  application:
    name: pam-emailer

  datasource:
    url: jdbc:postgresql://${DB_HOST:}:${DB_PORT:}/${DB_DATABASE:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

management:
  endpoints.web.exposure.include: prometheus
  endpoint:
    prometheus.enabled: true
    metrics.enabled: true
  prometheus.metrics.export.enabled: true