name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - '../../.nais/alerts.yml'
      - '.github/workflows/alerts.yml'
jobs:
  apply-alerts:
    name: Apply alerts to prod
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yml
