name: build-deploy-dev
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-dev.yml@v7
    permissions:
      actions: read
      contents: write
      security-events: write
      id-token: write
    with:
      JAVA_VERSION: 17
      NAIS_RESOURCE: naiserator.yml
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
